### ISSUE TITLE
[Not an issue] - How does your router work from only a RouterProvider and no outlet? 

### ISSUE THREAD

**Issue by swalker326** [diogoparente/mf-nested-vite#1]
I cloned it and its running on my machine, so I know it works. But how, lol? I'm stuck going on day 4 in my own project and trying to implement exactly this on a much much bigger scale. We're also migrating from craco webpack module federation to vite monorepo, I'm just dumb founded, as soon as I add the outlet to my host, my remote breaks.

**Comment by swalker326** [comment]
Okay, so I don't need an outlet, but for the life of me, I cannot figure out what this error is:

ReferenceError: __rf_placeholder__shareScope is not defined
    at wrapShareModule (https://localhost.lcp.ai:3000/assets/bootstrap-x8BTrjVI.js:28629:25)
    at https://localhost.lcp.ai:3000/assets/bootstrap-x8BTrjVI.js:28656:64

**Comment by varsha-saini-maersk** [comment]
Were you able to solve this issue.
